# vp-cpp-template CI default configuration
# Read "Documentation.odt" (LibreOffice) for more information.
# Regarding the build-stage adjust the number of CPUs used (2 in this example).

name: vp-cpp-template CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: [localrunner, ubuntu]
    steps:
      - uses: actions/checkout@v3
      - name: Build localdev image
        run: docker rmi localdev || true && docker build --rm -f Dockerfile_localDev --cpuset-cpus 0-1 -t localdev .
  
  test:
    runs-on: [localrunner, ubuntu]
    needs: [build]
    steps:
      - name: Run localdev image for moduleTesting
        run: docker rm moduleTesting || true && docker run --name moduleTesting --workdir /app/workdir/ localdev ./vp-cpp-template confModuleTesting-Ubuntu.cfg
      - name: Run localdev image for pythonTesting
        run: docker rm pythonTesting || true && docker run --name pythonTesting --workdir /app/python/ localdev python3 ExampleCTypes.py
